# Import Libraries

In [1]:
import pandas as pd
import tagui as t
import time

# Knowledge Base Setup

In [2]:
KB = 'Knowledge Base_Complete.xlsx'
df_time = pd.read_excel(KB,"Travel Time",index_col = 0)
df_ave_rent = pd.read_excel(KB,"Ave Rental",index_col = 0)

In [3]:
df_time.head()

,1,2,3,4,5,6,7,8,9,10,...,162,163,164,165,166,167,168,169,170,171
1,0,53,21,65,42,41,49,52,61,55,...,52,67,30,6,16,16,46,21,19,12
2,53,0,35,51,56,20,21,34,12,25,...,22,35,37,54,56,52,32,55,37,45
3,21,35,0,47,55,23,31,34,43,37,...,34,49,29,24,34,34,28,39,6,13
4,65,51,47,0,76,35,47,54,55,50,...,47,62,52,67,71,66,26,82,49,56
5,42,56,55,76,0,59,46,25,65,70,...,66,81,48,39,49,49,54,24,58,50

In [4]:
df_ave_rent = df_ave_rent.drop('MRT Code',axis=1)
df_ave_rent.head()

,Station Name,MRT Unique,Average Room Rental Prices (S$),Average 3-Room House Rental Prices (S$),Average 4-Room House Rental Prices (S$),Average 5-Room House Rental Prices (S$),Average Overall Whole-house Rental
Index,,,,,,,
1,Admiralty,NS10,1120,2000,2450,2500,2316.67
2,Aljunied,EW9,1743,2450,2600,3200,2750
3,Ang Mo Kio,NS16,1273,2300,2600,3000,2633.33
4,Bakau,SE3,1254,2300,2600,3000,2633.33
5,Bangkit,BP9,1106,2290,2450,2800,2513.33

In [5]:
df_ave_rent_minmax = df_ave_rent.drop('MRT Unique',axis=1)
df_ave_rent_ori_processed = df_ave_rent_minmax[df_ave_rent_minmax['Average Room Rental Prices (S$)'] != "No data"]
df_ave_rent_minmax = df_ave_rent_minmax[df_ave_rent_minmax['Average Room Rental Prices (S$)'] != "No data"]

for column in df_ave_rent_minmax.columns:
    if column == "Station Name":
        continue

    else:
        df_ave_rent_minmax[column] = (df_ave_rent_minmax[column] - df_ave_rent_minmax[column].min())/ (df_ave_rent_minmax[column].max() - df_ave_rent_minmax[column].min())

df_ave_rent_minmax.head()

,Station Name,Average Room Rental Prices (S$),Average 3-Room House Rental Prices (S$),Average 4-Room House Rental Prices (S$),Average 5-Room House Rental Prices (S$),Average Overall Whole-house Rental
Index,,,,,,
1,Admiralty,0.0889181,0,0.0357143,0,0
2,Aljunied,0.361805,0.28125,0.142857,0.466667,0.292135
3,Ang Mo Kio,0.155935,0.1875,0.142857,0.333333,0.213483
4,Bakau,0.147613,0.1875,0.142857,0.333333,0.213483
5,Bangkit,0.0827858,0.18125,0.0357143,0.2,0.132584

In [6]:
# Max and Mins for normalization purposes
time_min = 0
time_max = 97

room_rent_min = df_ave_rent_ori_processed['Average Room Rental Prices (S$)'].min()
room_rent_max = df_ave_rent_ori_processed['Average Room Rental Prices (S$)'].max()
house_rent_min = df_ave_rent_ori_processed['Average Overall Whole-house Rental'].min()
house_rent_max = df_ave_rent_ori_processed['Average Overall Whole-house Rental'].max()

In [7]:
df_index = df_ave_rent.drop(["MRT Unique",
                             "Average Room Rental Prices (S$)",
                             "Average 3-Room House Rental Prices (S$)",
                             "Average 4-Room House Rental Prices (S$)",
                             "Average 5-Room House Rental Prices (S$)",
                            "Average Overall Whole-house Rental"],axis=1)
df_index.head()

      Station Name
Index
1        Admiralty
2         Aljunied
3       Ang Mo Kio
4            Bakau
5          Bangkit

In [8]:
df_MRT_code = pd.read_excel('Knowledge Base_Complete.xlsx',"Ave Rental",index_col = 0)
df_MRT_code = df_MRT_code.drop(['MRT Unique',
                                "Average Room Rental Prices (S$)",
                             "Average 3-Room House Rental Prices (S$)",
                             "Average 4-Room House Rental Prices (S$)",
                             "Average 5-Room House Rental Prices (S$)",
                            "Average Overall Whole-house Rental"],axis=1)

df_MRT_code = df_MRT_code.rename(columns={'MRT Code':'MRT ID'})
df_MRT_code = df_MRT_code.set_index('Station Name')
df_MRT_code.head(50)
# df_MRT_code = df_ave_rent.drop(["Average Room Rental Prices (S$)",
#                              "Average 3-Room House Rental Prices (S$)",
#                              "Average 4-Room House Rental Prices (S$)",
#                              "Average 5-Room House Rental Prices (S$)",
#                             "Average Overall Whole-house Rental"],axis=1)

# df_MRT_code = df_MRT_code.rename(columns={'MRT Unique':'MRT ID'})
# df_MRT_code = df_MRT_code.set_index('Station Name')
# df_MRT_code.head()

                       MRT ID
Station Name
Admiralty                NS10
Aljunied                  EW9
Ang Mo Kio               NS16
Bakau                     SE3
Bangkit                   BP9
Bartley                  CC12
Bayfront             CE1 DT16
Beauty World              DT5
Bedok                     EW5
Bedok North              DT29
Bedok Reservoir          DT30
Bencoolen                DT21
Bendemeer                DT23
Bishan              NS17 CC15
Boon Keng                 NE9
Boon Lay                 EW27
Botanic Gardens      CC19 DT9
Braddell                 NS18
Bras Basah                CC2
Bright Hill               TE7
Buangkok                 NE15
Bugis               EW12 DT14
Bukit Batok               NS2
Bukit Gombak              NS3
Bukit Panjang         DT1 BP6
Buona Vista         EW21 CC22
Caldecott                CC17
Canberra                 NS12
Cashew                    DT2
Changi Airport            CG2
Cheng Lim                 SW1
Chinatown            NE4 DT19
Chinese Garden           EW25
Choa Chu Kang         NS4 BP1
City Hall           NS25 EW13
Clarke Quay               NE5
Clementi                 EW23
Commonwealth             EW20
Compassvale               SE1
Coral Edge                PE3
Cove                      PE1
Dakota                    CC8
Damai                     PE7
Dhoby Ghaut      NS24 NE6 CC1
Dover                    EW22
Downtown                 DT17
Esplanade                 CC3
Eunos                     EW7
Expo                 CG1 DT35
Fajar                    BP10

# Dictionary and Functions Setup

In [9]:
# MRT Index by index (e.g. 1: Admiralty, 2: Aljunied,  etc)
MRT_index_name = df_index.to_dict()

# MRT index by name (e.g. Admiralty: 1, Aljunied: 2, etc)
MRT_name_index = {value: key for key, value in MRT_index_name['Station Name'].items()}

print(MRT_index_name)
print()

{'Station Name': {1: 'Admiralty', 2: 'Aljunied', 3: 'Ang Mo Kio', 4: 'Bakau', 5: 'Bangkit', 6: 'Bartley', 7: 'Bayfront', 8: 'Beauty World', 9: 'Bedok', 10: 'Bedok North', 11: 'Bedok Reservoir', 12: 'Bencoolen', 13: 'Bendemeer', 14: 'Bishan', 15: 'Boon Keng', 16: 'Boon Lay', 17: 'Botanic Gardens', 18: 'Braddell', 19: 'Bras Basah', 20: 'Bright Hill', 21: 'Buangkok', 22: 'Bugis', 23: 'Bukit Batok', 24: 'Bukit Gombak', 25: 'Bukit Panjang', 26: 'Buona Vista', 27: 'Caldecott', 28: 'Canberra', 29: 'Cashew', 30: 'Changi Airport', 31: 'Cheng Lim', 32: 'Chinatown', 33: 'Chinese Garden', 34: 'Choa Chu Kang', 35: 'City Hall', 36: 'Clarke Quay', 37: 'Clementi', 38: 'Commonwealth', 39: 'Compassvale', 40: 'Coral Edge', 41: 'Cove', 42: 'Dakota', 43: 'Damai', 44: 'Dhoby Ghaut', 45: 'Dover', 46: 'Downtown', 47: 'Esplanade', 48: 'Eunos', 49: 'Expo', 50: 'Fajar', 51: 'Farmway', 52: 'Farrer Park', 53: 'Farrer Road', 54: 'Fernvale', 55: 'Fort Canning', 56: 'Gardens by the Bay', 57: 'Geylang Bahru', 58: 'Great World', 59: 'Gul Circle', 60: 'HarbourFront', 61: 'Havelock', 62: 'Haw Par Villa', 63: 'Hillview', 64: 'Holland Village', 65: 'Hougang', 66: 'Jalan Besar', 67: 'Jelapang', 68: 'Joo Koon', 69: 'Jurong East', 70: 'Kadaloor', 71: 'Kaki Bukit', 72: 'Kallang', 73: 'Kangkar', 74: 'Keat Hong', 75: 'Kembangan', 76: 'Kent Ridge', 77: 'Khatib', 78: 'King Albert Park', 79: 'Kovan', 80: 'Kranji', 81: 'Kupang', 82: 'Labrador Park', 83: 'Lakeside', 84: 'Lavender', 85: 'Layar', 86: 'Lentor', 87: 'Little India', 88: 'Lorong Chuan', 89: 'MacPherson', 90: 'Marina Bay', 91: 'Marina South Pier', 92: 'Marsiling', 93: 'Marymount', 94: 'Mattar', 95: 'Maxwell', 96: 'Mayflower', 97: 'Meridian', 98: 'Mountbatten', 99: 'Napier', 100: 'Newton', 101: 'Nibong', 102: 'Nicoll Highway', 103: 'Novena', 104: 'Oasis', 105: 'one-north', 106: 'Orchard', 107: 'Orchard Boulevard', 108: 'Outram Park', 109: 'Pasir Panjang', 110: 'Pasir Ris', 111: 'Paya Lebar', 112: 'Pending', 113: 'Petir', 114: 'Phoenix', 115: 'Pioneer', 116: 'Potong Pasir', 117: 'Promenade', 118: 'Punggol', 119: 'Punggol Point', 120: 'Queenstown', 121: 'Raffles Place', 122: 'Ranggung', 123: 'Redhill', 124: 'Renjong', 125: 'Riviera', 126: 'Rochor', 127: 'Rumbia', 128: 'Sam Kee', 129: 'Samudera', 130: 'Segar', 131: 'Sembawang', 132: 'Sengkang', 133: 'Senja', 134: 'Serangoon', 135: 'Shenton Way', 136: 'Simei', 137: 'Sixth Avenue', 138: 'Somerset', 139: 'Soo Teck', 140: 'South View', 141: 'Springleaf', 142: 'Stadium', 143: 'Stevens', 144: 'Sumang', 145: 'Tai Seng', 146: 'Tampines', 147: 'Tampines East', 148: 'Tampines West', 149: 'Tan Kah Kee', 150: 'Tanah Merah', 151: 'Tanjong Pagar', 152: 'Teck Whye', 153: 'Telok Ayer', 154: 'Telok Blangah', 155: 'Thanggam', 156: 'Tiong Bahru', 157: 'Toa Payoh', 158: 'Tongkang', 159: 'Tuas Crescent', 160: 'Tuas Link', 161: 'Tuas West Road', 162: 'Ubi', 163: 'Upper Changi', 164: 'Upper Thomson', 165: 'Woodlands', 166: 'Woodlands North', 167: 'Woodlands South', 168: 'Woodleigh', 169: 'Yew Tee', 170: 'Yio Chu Kang', 171: 'Yishun'}}

In [10]:
MRT_codes = df_MRT_code.to_dict()
print(MRT_codes)

{'MRT ID': {'Admiralty': 'NS10', 'Aljunied': 'EW9', 'Ang Mo Kio': 'NS16', 'Bakau': 'SE3', 'Bangkit': 'BP9', 'Bartley': 'CC12', 'Bayfront': 'CE1 DT16', 'Beauty World': 'DT5', 'Bedok': 'EW5', 'Bedok North': 'DT29', 'Bedok Reservoir': 'DT30', 'Bencoolen': 'DT21', 'Bendemeer': 'DT23', 'Bishan': 'NS17 CC15', 'Boon Keng': 'NE9', 'Boon Lay': 'EW27', 'Botanic Gardens': 'CC19 DT9', 'Braddell': 'NS18', 'Bras Basah': 'CC2', 'Bright Hill': 'TE7', 'Buangkok': 'NE15', 'Bugis': 'EW12 DT14', 'Bukit Batok': 'NS2', 'Bukit Gombak': 'NS3', 'Bukit Panjang': 'DT1 BP6', 'Buona Vista': 'EW21 CC22', 'Caldecott': 'CC17', 'Canberra': 'NS12', 'Cashew': 'DT2', 'Changi Airport': 'CG2', 'Cheng Lim': 'SW1', 'Chinatown': 'NE4 DT19', 'Chinese Garden': 'EW25', 'Choa Chu Kang': 'NS4 BP1', 'City Hall': 'NS25 EW13', 'Clarke Quay': 'NE5', 'Clementi': 'EW23', 'Commonwealth': 'EW20', 'Compassvale': 'SE1', 'Coral Edge': 'PE3', 'Cove': 'PE1', 'Dakota': 'CC8', 'Damai': 'PE7', 'Dhoby Ghaut': 'NS24 NE6 CC1', 'Dover': 'EW22', 'Downtown': 'DT17', 'Esplanade': 'CC3', 'Eunos': 'EW7', 'Expo': 'CG1 DT35', 'Fajar': 'BP10', 'Farmway': 'SW2', 'Farrer Park': 'NE8', 'Farrer Road': 'CC20', 'Fernvale': 'SW5', 'Fort Canning': 'DT20', 'Gardens by the Bay': 'TE22', 'Geylang Bahru': 'DT24', 'Great World': 'TE15', 'Gul Circle': 'EW30', 'HarbourFront': 'NE1 CC29', 'Havelock': 'TE16', 'Haw Par Villa': 'CC25', 'Hillview': 'DT3', 'Holland Village': 'CC21', 'Hougang': 'NE14', 'Jalan Besar': 'DT22', 'Jelapang': 'BP12', 'Joo Koon': 'EW29', 'Jurong East': 'NS1 EW24', 'Kadaloor': 'PE5', 'Kaki Bukit': 'DT28', 'Kallang': 'EW10', 'Kangkar': 'SE4', 'Keat Hong': 'BP3', 'Kembangan': 'EW6', 'Kent Ridge': 'CC24', 'Khatib': 'NS14', 'King Albert Park': 'DT6', 'Kovan': 'NE13', 'Kranji': 'NS7', 'Kupang': 'SW3', 'Labrador Park': 'CC27', 'Lakeside': 'EW26', 'Lavender': 'EW11', 'Layar': 'SW6', 'Lentor': 'TE5', 'Little India': 'NE7 DT12', 'Lorong Chuan': 'CC14', 'MacPherson': 'CC10 DT26', 'Marina Bay': 'NS27 CE2', 'Marina South Pier': 'NS28', 'Marsiling': 'NS8', 'Marymount': 'CC16', 'Mattar': 'DT25', 'Maxwell': 'TE18', 'Mayflower': 'TE6', 'Meridian': 'PE2', 'Mountbatten': 'CC7', 'Napier': 'TE12', 'Newton': 'NS21 DT11', 'Nibong': 'PW5', 'Nicoll Highway': 'CC5', 'Novena': 'NS20', 'Oasis': 'PE6', 'one-north': 'CC23', 'Orchard': 'NS22', 'Orchard Boulevard': 'TE13', 'Outram Park': 'EW16 NE3', 'Pasir Panjang': 'CC26', 'Pasir Ris': 'EW1', 'Paya Lebar': 'EW8 CC9', 'Pending': 'BP8', 'Petir': 'BP7', 'Phoenix': 'BP5', 'Pioneer': 'EW28', 'Potong Pasir': 'NE10', 'Promenade': 'CC4 DT15', 'Punggol': 'NE17 PTC', 'Punggol Point': 'PW3', 'Queenstown': 'EW19', 'Raffles Place': 'NS26 EW14', 'Ranggung': 'SE5', 'Redhill': 'EW18', 'Renjong': 'SW8', 'Riviera': 'PE4', 'Rochor': 'DT13', 'Rumbia': 'SE2', 'Sam Kee': 'PW1', 'Samudera': 'PW4', 'Segar': 'BP11', 'Sembawang': 'NS11', 'Sengkang': 'NE16 STC', 'Senja': 'BP13', 'Serangoon': 'NE12 CC13', 'Shenton Way': 'TE19', 'Simei': 'EW3', 'Sixth Avenue': 'DT7', 'Somerset': 'NS23', 'Soo Teck': 'PW7', 'South View': 'BP2', 'Springleaf': 'TE4', 'Stadium': 'CC6', 'Stevens': 'DT10', 'Sumang': 'PW6', 'Tai Seng': 'CC11', 'Tampines': 'EW2 DT32', 'Tampines East': 'DT33', 'Tampines West': 'DT31', 'Tan Kah Kee': 'DT8', 'Tanah Merah': 'EW4 CG', 'Tanjong Pagar': 'EW15', 'Teck Whye': 'BP4', 'Telok Ayer': 'DT18', 'Telok Blangah': 'CC28', 'Thanggam': 'SW4', 'Tiong Bahru': 'EW17', 'Toa Payoh': 'NS19', 'Tongkang': 'SW7', 'Tuas Crescent': 'EW31', 'Tuas Link': 'EW33', 'Tuas West Road': 'EW32', 'Ubi': 'DT27', 'Upper Changi': 'DT34', 'Upper Thomson': 'TE8', 'Woodlands': 'NS9 TE2', 'Woodlands North': 'TE1 RTS', 'Woodlands South': 'TE3', 'Woodleigh': 'NE11', 'Yew Tee': 'NS5', 'Yio Chu Kang': 'NS15', 'Yishun': 'NS13'}}

# Nearest Station Codes

In [11]:
def find_nearest_station(CoA_postcodes):
    '''for CoA, just input a list of 6-digit postcode'''
    closest_stations = []
    location_names = []
    t.init()
    attempts = 0
    
    while attempts < 4:
        try:
            for i in range(len(CoA_postcodes)):
                t.url("https://www.streetdirectory.com/")
                t.wait(3)
                if t.present('//a[@class="btn_close"]'):
                    t.click('//a[@class="btn_close"]')
                    t.wait(3)

                t.type('//input[@id="q"]',list(CoA_postcodes)[i])
                t.click('//input[@id="search_button"]')
                t.wait(2)
                location_name = t.read('//h1[@style="font-weight: bold; font-family: tahoma; line-height: 15px; font-size: 14px;"]')
                location_names.append(location_name)
                t.click('//div[@id="sidenav_direction"]')
                t.wait(2)

                if t.present('//a[@class="btn_close"]'):
                    t.click('//a[@class="btn_close"]')
                    t.wait(3)

                if t.present('(//div[@style="font-family: tahoma; font-size: 12px; width: 173px;"])[2]'):
                    closest_station = t.read('(//div[@style="font-family: tahoma; font-size: 12px; width: 173px;"])[2]')
                    closest_station = closest_station[:closest_station.find(" MRT")]
                    closest_stations.append(closest_station)

                else:
                    t.wait(5)
                    if t.present('//a[@class="btn_close"]'):
                        t.click('//a[@class="btn_close"]')
                    t.wait(3)
                    t.click('//div[@id="sidenav_nearby_location"]')
                    t.wait(2)
                    closest_station = t.read('(//div[@style="font-size:14px;font-weight:normal;"])[1]')
                    closest_station = closest_station[:closest_station.find(" MRT")]
                    closest_stations.append(closest_station)
            break
        
        except:
            attempts += 1
            continue

    t.close()

    return closest_stations, location_names

In [12]:
def ave_rental_calculate(house_type,index):
    if df_ave_rent["Average Room Rental Prices (S$)"][index] == "No data":
        return "No data"
    else:
        if house_type.lower() == "room":
            ave_rental = float(df_ave_rent_minmax["Average Room Rental Prices (S$)"][index])
        elif house_type.lower() == "entire house":
            ave_rental = float(df_ave_rent_minmax["Average Overall Whole-house Rental"][index])
        else:
            ave_rental = "Invalid housetype"

        return ave_rental

In [13]:
def normalize_all(house_type,budget,comfortable_travel_time):
    if house_type.lower() == "room":
        budget = (budget - room_rent_min) / (room_rent_max - room_rent_min)
    else:
        budget = (budget - house_rent_min) / (house_rent_max - house_rent_min)
    
    comfortable_travel_time = comfortable_travel_time / time_max
    
    return budget, comfortable_travel_time

In [14]:
def shortlist_stations(closest_station, budget_weight = 0.2, time_weight = 0.65, shortlist_num = 3):
    scores, stations_and_time, time_ave = [],[],[]

    for i in range(1,172):
        average_rental = df_ave_rent["Average Room Rental Prices (S$)"][i]
        average_rental_norm = ave_rental_calculate(house_type,i)

        if average_rental_norm == "No data":
            continue

        else:
            time_total = 0
            for station in closest_station:
                CoA_time = float(df_time[i][MRT_name_index[station]])/time_max
                time_total += CoA_time
                
            time_average = time_total/len(closest_station)    
            
            # Budget bonus rules
            if average_rental>0.7*budget and average_rental < 1.1*budget:
                budget_bonus = 1.5
            elif average_rental>0.5*budget and average_rental<0.7*budget:
                budget_bonus = 1
            elif average_rental>1.5*budget and average_rental<2.0*budget:
                budget_bonus = -1
            elif average_rental>2.0*budget and average_rental<2.5*budget:
                budget_bonus = -2.1
            elif average_rental>2.5*budget:
                budget_bonus = -5
            else:
                budget_bonus = 0

            # Time penalty rules:
            if time_average > comfortable_travel_time:
                time_penalty = 0.5*float(time_average*time_max - comfortable_travel_time)
            else:
                time_penalty = 0

            # total score above would result in "the smaller the better". Score is inversed to generate a "bigger score better" setting
            total_score = (1/(0.2*average_rental_norm+0.65*time_average+1))*10 + budget_bonus - time_penalty
            scores.append(round(total_score,4))
            stations_and_time.append([MRT_index_name['Station Name'][i],time_average*time_max])

    scores, stations_and_time = zip(*sorted(zip(scores, stations_and_time),reverse = True))
    
    stations = []
    ave_travel_time = []
    for item in stations_and_time:
        stations.append(item[0])
        ave_travel_time.append(item[1])
    
    stations = tuple(stations)
    ave_travel_time = tuple(ave_travel_time)
    
    return scores[:shortlist_num], stations[:shortlist_num], ave_travel_time[:shortlist_num]

# Utilities

In [15]:
def scoring(price,
            travel_time,
            budget,
            house_type,
            comfortable_travel_time):
    
    housing_dict = {'room':{'min':917,
                           'max':3200},             
            'entire house':{'min':2317,
                            'max':3800}}
    
    hd = housing_dict[house_type.lower()]
    norm_price = (price - hd['min']/(hd['max']-hd['min']))
    norm_travel_time = travel_time/97 # time_max = 97, time_min = 0
    
    # Budget Bonus scoring to boost properties around the budget set.
    # Prevents the situation where lowest price is always favoured regardless of budget.
    if price>0.7*budget and price< 1.1*budget:
        budget_bonus = 1.5
    elif price>0.5*budget and price<0.7*budget:
        budget_bonus = 1
    elif price>1.5*budget and price<2.0*budget:
        budget_bonus = -1
    elif price>2.0*budget:
        budget_bonus = -2.1
    elif price>2.5*budget:
        budget_bonus = -5
    else:
        budget_bonus = 0
    
    # Travel Time Penalty if exceed the 
    if float(travel_time)>comfortable_travel_time:
        time_penalty = 0.5*float(travel_time-comfortable_travel_time)
    else:
        time_penalty = 0
    
    # in the nearest MRT formula, the bigger weight is on travel time as the price reflects an average
    
    score = (1/(0.65*norm_price+0.2*norm_travel_time+1))*10 + budget_bonus - time_penalty
    
    return score

In [16]:
def lets_wait(target_element):
    start_time = time.time()
    time_lapsed = 0
    while not t.present(target_element) and time_lapsed < 8:
        t.wait(1)
        end_time = time.time()
        time_lapsed = end_time - start_time
    return target_element

In [17]:
def time_converter(input_data):
    input_time = [time for time in input_data.split() if time.isnumeric()]
    input_unit = input_data.split()
    if len(input_time) == 2:
        hour_to_min = int(input_time[0]) * 60
        total_time = hour_to_min + int(input_time[1])
    
    elif len(input_time) == 1 and ("hr" not in input_unit or 'h' not in input_unit):
        total_time = (input_time[0])
    
    elif len(input_time) == 1:
        total_time = int(input_time[0]) * 60
    
    else:
        total_time = 0
    
    return total_time

In [18]:
def shortlist_generation(prop_titles,prop_addresses,prop_prices,travel_times,links,scores):
    if (len(prop_titles)+len(prop_addresses)+len(prop_prices)+len(travel_times)+len(links))/5 != len(scores):
        return "Scrape does not tally"
#         return len(prop_titles),len(prop_addresses),len(prop_prices),len(travel_times),len(links), len(scores)
    else:
        shortlist = pd.DataFrame({'Property' : prop_titles,
                                          'Address' : prop_addresses,
                                          'Price (S$/mo)' : prop_prices,
                                          'Travel Time (mins)': travel_times,
                                         'Property Score': scores,
                                         'Links' : links})

        shortlist = shortlist.sort_values(by=['Property Score'],ascending=False)

        return shortlist

In [19]:
def ave_time_generation(address,CoA,CoA_Name,timecheck_index):
    tt_total = 0.0
    for i in range(len(list(CoA))):
        tt = time_check(address,f"Singapore {CoA[i]}",CoA_Name[i],timecheck_index)
        tt_total += float(tt)
    ave_time = float(tt_total) / len(CoA)
    return ave_time

In [20]:
def dummy_fillers(pipeline, shortlist_num = 5):
    chromosome_1 = [i+1 for i in range(3)] # MRT Search Method
    chromosome_2 = [i+1 for i in range(8)] # Sort Method
    chromosome_3 = [i+1 for i in range(3)] # Timecheck Method
    chromosome_4 = [i+1 for i in range(2)] # Scraping Method
    
    all_chromos = [chromosome_1, chromosome_2, chromosome_3, chromosome_4]
    
    for pipes, chromos in zip(pipeline, all_chromos):
        if pipes not in chromos:
            dummy_list = []
            dummy_list = dummy_list + [10000]*(shortlist_num - len(dummy_list))
            prop_titles,prop_addresses,prop_prices,travel_times,links,scores = [dummy_list.copy() for _ in range(6)]
            shortlist = shortlist_generation(prop_titles,prop_addresses,prop_prices,travel_times,links,scores)
            time_lapsed = 1000
            break

        else:
            shortlist, time_lapsed = "Pass","Pass"
            
    return shortlist, time_lapsed

In [21]:
haha, haha2 = dummy_fillers([1,2,2,1])
# print(haha)
# print(haha2)
if haha2 == "Pass":
    print(haha2)
else:
    print(haha)

Pass

# Scraping and Shortlisting Codes

In [22]:
def URL_generator(max_price, house_type, mrt_name, MRT_method_index, sort_method_index, website='property guru'):
    
    global df_MRT_code
    url_adapted = mrt_name.replace(" ","+")
    MRT_code = df_MRT_code['MRT ID'][mrt_name]
    split_code = MRT_code.split()

    url_mrt = ""
    concat_code = ""
    for code in split_code:
        url_mrt += f"&MRT_STATIONS[]={code}"
        concat_code += f"/{code}"
    concat_code = concat_code[1:]
    url_mrt = url_mrt[1:]
    
    url_details = {'property guru':{'url':'https://www.propertyguru.com.sg/',
                               'rental housing':'property-for-rent?market=residential&listing_type=rent&',
                               'max price':f'maxprice={str(max_price)}&',
                                   'room':'beds[]=-1&',
                                   'entire house':'beds[]=0&beds[]=1&beds[]=2&beds[]=3&beds[]=4&beds[]=5&',
                                   'search true':'search=true',
                                   'MRT search method':{'1':f"{url_mrt}&freetext={concat_code}+{url_adapted}+MRT&",
                                                       '2':f"freetext={url_adapted}+MRT&",
                                                       '3':f"freetext={url_adapted}&"},
                                   'sort method':{"1": '', # Recommended
                                                  "2": '&sort=date&order=desc', # Newest
                                                  "3": '&sort=price&order=asc', # Lowest Price
                                                  "4": '&sort=price&order=desc', # Highest Price
                                                  "5": '&sort=psf&order=asc', # PSF (low-high)
                                                  "6": '&sort=psf&order=desc', # PSF (high-low)
                                                  "7": '&sort=size&order=asc', # Size (low-high)
                                                  "8": '&sort=size&order=desc'}}} # Size (high-low)
    
    
    ud = url_details[website.lower()]
    
    base = ud['url']
    rental_housing = ud['rental housing'] 
    max_price = ud['max price']
    house_type = ud[house_type.lower()]
    mrt_search = ud['MRT search method'][str(MRT_method_index)]
    ending = ud['search true']
    sort_method = ud['sort method'][str(sort_method_index)]
    
    full_url = "".join([base,rental_housing,max_price,house_type,mrt_search,ending,sort_method])
    return full_url

In [23]:
def time_check(start_point,end_point,end_point_name,option_index):
    option_index = str(option_index)
    
    site_details = {"1":{"url":'https://www.google.com/maps/dir///',
                        "start box":'(//input[@class="tactile-searchbox-input"])[1]',
                        "end box":'(//input[@class="tactile-searchbox-input"])[2]',
                        "search button":'(//button[@data-tooltip="Search"])[2]',
                        "public transport option": '//img[@data-tooltip="Transit"]',
                        "depart by options":'//div[@id=":3"]',
                        "select depart at":'//div[@id=":1"]',
                        "departing time box":'//input[@name="transit-time"]',
                        "12:30pm option":'//div[@id=":p"]',
                        "travel times":'//div[@class="Fk3sm fontHeadlineSmall"]'},
                    
                   "2":{"url":'https://www.streetdirectory.com/travel/',
                        "close ad":'//a[@class="btn_close"]',
                        "start box":'//input[@id="travel_from"]',
                        "end box":'//input[@id="travel_to"]',
                        "search button":'//a[@id="go_button"]',
                        "confirm locations":'(//tr[@class="information"])[1]',
                        "select depart at":'//input[@id="time"]',
                        "departing am/pm":'(//a[@class="ptTimeSelectHr ui-state-default"])[2]',
                        "12:30pm option":'(//a[@class="ptTimeSelectHr ui-state-default"])[14]',
                        "confirm timing":'//a[@onclick="jQuery.ptTimeSelect.setTime()"]'},
                   
                    "3": {"url":'https://gothere.sg/maps',
                        "search box":'//input[@id="q"]',
                         "search button": '//input[@id="ss"]'}}
    
    min_time = 1000
    # method begins here:
    tc = site_details[option_index]
    t.url(tc['url'])
    
    if option_index == "1": # Google Maps
        t.type(tc["start box"],start_point)
        t.type(tc["end box"], end_point)
        t.click(tc["search button"])
        
        t.click(lets_wait(tc["public transport option"]))
        t.wait(3)
        t.click(tc["depart by options"])
        t.click(lets_wait(tc["select depart at"]))
        t.type(tc["departing time box"],"[clear]12:30pm[enter]")
        t.wait(3)
        
        for i in range(1,t.count(tc["travel times"])+1):
            travel_time = time_converter(t.read(f'({tc["travel times"]})[{i}]'))
            if int(travel_time) < int(min_time):
                min_time = travel_time
    
    elif option_index == "2": # Street Directory
        start_time = time.time()
        time_lapse = 0
        while not t.present(tc["close ad"]) and time_lapse < 8 :
            t.wait(1)
            end_time = time.time()
            time_lapse = end_time - start_time
        
        if t.present(tc["close ad"]):
            t.click(tc["close ad"])
            
            
        t.type(tc["start box"],start_point+'[enter]')
        t.type(tc["end box"],end_point_name+'[enter]')
        t.click(tc["search button"])
        t.wait(2)

        while t.present(tc["confirm locations"]):
            t.click(tc["confirm locations"])
            t.wait(2)
        
        for process in ["select depart at", "departing am/pm", "12:30pm option", "confirm timing"]:
            t.click(tc[process])

        for mode in ['bus','busmrt']:
            travel_time = time_converter(t.read(f'//span[@id="{mode}_time"]'))
            if int(travel_time) < int(min_time):
                min_time = travel_time
    
    
    elif option_index == "3": # gothere.sg
        t.type(tc['search box'],f'from {start_point} to {end_point} at 12:30pm[enter]')
        t.click(tc['search button'])
        t.wait(2)

        for mode in ["bus","train"]:
            t.click(f'//li[@id="{mode}"]')
            
            for i in range(1,t.count(f'//div[@mode="{mode}"]/p[@class="n1"]')+1):
                travel_time = time_converter(t.read(f'(//div[@mode="{mode}"]/p[@class="n1"])[{i}]'))
                if int(travel_time) < int(min_time):
                    min_time = travel_time
        
    return min_time

In [24]:
def shortlist_properties(url, CoA, CoA_Name, budget, house_type, comfortable_travel_time, 
                          search_method_index, timecheck_index, time_average, 
                         shortlist_num = 5, website='property guru', no_change_max = 7):
    '''Function to scrape website and shortlist properties based on travel time and price. 
    CoA here should be in a list format'''
    
    website_details = {'property guru':{'no results':'''//h3[text()="Sorry, we couldn't find any results for:"])''',
                                        'search box':'//input[@placeholder="Search Location"]',
                                        'prop title':'//div[@class="gallery-container"]/a/@title',
                                       'prop address':'//span[@itemprop="streetAddress"]',
                                        'prop price':'//li[@class="list-price pull-left"]/span[@class="price"]',
                                        'prop link':'(//div[@class="gallery-container"]/a/@href)',
                                        'next page':'//li[@class="pagination-next"]/a'}}
    
    wd = website_details[website]
    t.init()
    t.url(url)
    
    # this loop is to prevent captcha from stopping the process. User needs to click the verify in order to proceed.
    while not t.present(wd['search box']):
        t.wait(1)
    
    
    next_page = True
    t.wait(4)
    if t.present(wd['no results']):
        return "Sorry, we couldn't find any results. Please update your search criteria"
    
    elif str(search_method_index) == "1":
        # Initialisation
        prop_titles, prop_addresses, prop_prices, links, travel_times, scores, temp_address_memory, temp_time_memory = [[] for _ in range(8)]

        while next_page:
            lets_wait(wd['prop address'])
            prop_no = t.count(wd['prop address'])
            for i in range(1, prop_no + 1):
                # Reading
                prop_title = t.read(f"({wd['prop title']})[{i}]")
                prop_address = t.read(f"({wd['prop address']})[{i}]")
                price = t.read(f"({wd['prop price']})[{i}]")
                price = int(price.replace(',',''))
                link = t.read(f"{wd['prop link']}[{i}]")
                
                # Appending
                prop_titles.append(prop_title)
                prop_addresses.append(prop_address)
                prop_prices.append(price)
                links.append(link)

            if t.present(wd['next page']):
                t.click(wd['next page'])
                t.wait(3)
                
            else:
                next_page = False


        for address in prop_addresses:
            if address not in temp_address_memory:
                ave_time = ave_time_generation(prop_address,CoA,CoA_Name,timecheck_index)
                travel_times.append(ave_time)
                temp_address_memory.append(address) # Memory component to save redundant searches
                temp_time_memory.append(ave_time) # Memory to recall the saved address
            else:
                travel_times.append(temp_time_memory[temp_address_memory.index(address)])

            for i in range(len(prop_addresses)):
                prop_score = scoring(prop_prices[i],travel_times[i],budget,house_type,comfortable_travel_time)
                scores.append(prop_score)
        
        shortlist = shortlist_generation(prop_titles,prop_addresses,prop_prices,travel_times,links,scores)
        
    elif str(search_method_index) == "2":
        # Initialisation
        scores = []
        scores = scores + [0]*(shortlist_num - len(scores))
        prop_titles, prop_addresses, prop_prices, links, travel_times = [scores.copy() for _ in range(5)]
        temp_address_memory, temp_time_memory = [],[]
        no_change_count = 0

        while next_page:
            lets_wait(wd['prop address'])
            prop_no = t.count(wd['prop address'])

            for i in range(1, prop_no + 1):
                skip_timecheck = False
                prop_address = t.read(f"({wd['prop address']})[{i}]")
                print(prop_address)
                price = t.read(f"({wd['prop price']})[{i}]")
                price = int(price.replace(',',''))
                print(price)
                prop_score = scoring(price,time_average,budget,house_type,comfortable_travel_time) #ave_travel_time here is station[1] in nearest station
                print(prop_score)

                for j in range(len(scores)):
                    if prop_score > scores[j] and prop_address != "":
                        link = t.read(f"{wd['prop link']}[{i}]")
                        prop_title = t.read(f"({wd['prop title']})[{i}]")
                        print(prop_title)
                        
                        # Removing initialized 0s
                        scores.remove(scores[j])
                        prop_titles.remove(prop_titles[j])
                        prop_addresses.remove(prop_addresses[j])
                        prop_prices.remove(prop_prices[j])
                        links.remove(links[j])
                        travel_times.remove(travel_times[j])
                        
                        # Appending new information
#                         scores.append(prop_score)
                        prop_titles.append(prop_title)
                        prop_addresses.append(prop_address) 
                        prop_prices.append(price)
                        links.append(link)
                        skip_timecheck = False
                        break
                    else:
                        skip_timecheck = True


                if skip_timecheck:
                    no_change_count += 1
                    if no_change_count > 6:
                        break
                    else:
                        continue

                else:           
                    no_change_count = 0
                    if prop_address not in temp_address_memory:
                        current_url = t.url()
                        ave_time = ave_time_generation(prop_address,CoA,CoA_Name,timecheck_index)
                        travel_times.append(ave_time)
                        temp_address_memory.append(prop_address) # Memory component to save redundant searches
                        temp_time_memory.append(ave_time) # Memory to recall the saved address
                        t.url(current_url)
                    else:
                        travel_times.append(temp_time_memory[temp_address_memory.index(prop_address)])
                    
                    prop_score = scoring(price,ave_time,budget,house_type,comfortable_travel_time)
                    scores.append(prop_score)


            if no_change_count > no_change_max:
                break

            elif t.present(wd['next page']):
                t.click(wd['next page'])
                t.wait(3)
            else:
                next_page = False

            shortlist = shortlist_generation(prop_titles,prop_addresses,prop_prices,travel_times,links,scores)
    else:
        shortlist = "Search Error"
    
    t.close()
    return shortlist

# Pipeline Assembly

In [25]:
def process_pipeline(CoA,CoA_Name,budget,house_type,comfortable_travel_time, # Obtained from user 
                     time_average, mrt_name, # Obtained from for-loop calculation 
                     pipeline): # Set by us
    '''Function to arrange the process flow. Please note that CoA and Pipeline parameters must be in lists
    e.g of CoA = [111234,234000]
    e.g. of Pipeline = [1,2,1,1]'''
    
    dummy_check1, dummy_check2 = dummy_fillers(pipeline)
    if dummy_check2 == "Pass":
        start_time = time.time()

        URL = URL_generator(budget, house_type, mrt_name, pipeline[0], pipeline[1]) #
        shortlist = shortlist_properties(URL, CoA, CoA_Name, budget, house_type, comfortable_travel_time, pipeline[2], pipeline[3], time_average)

        end_time = time.time()
        time_lapsed = end_time - start_time
    
    else:
        shortlist, time_lapsed = dummy_check1, dummy_check2
#     print(f"Process took {time_lapsed} seconds")
    
    return shortlist, time_lapsed

# Form Input

In [26]:
house_type = "Room"
budget = 1200
comfortable_travel_time = 30 # in  minutes

budget_norm, comfortable_travel_time_norm = normalize_all(house_type,budget,comfortable_travel_time)
# Centre of activities (CoA) are areas 

CoA1 = "760329"
CoA2 = "271030"

# Running the Code

In [27]:
to_be_concatenated = []
start_time = time.time()

closest_station,location_name = find_nearest_station([CoA1,CoA2])
scores, stations, ave_travel_time = shortlist_stations(closest_station, shortlist_num = 1)
for i in range(len(stations)):
    shortlists, time_lapsed = process_pipeline( CoA = [CoA1,CoA2],
                                                       budget = budget,
                                                       CoA_Name = location_name,
                                                       house_type = house_type,
                                                       comfortable_travel_time = comfortable_travel_time,
                                                       time_average = ave_travel_time[i],
                                                       mrt_name = stations[i],
                                                       pipeline = [2,1,2,2])
    to_be_concatenated.append(shortlists)
    
    
shortlisted_props = pd.concat(to_be_concatenated)
end_time = time.time()
total_time_lapsed = end_time - start_time

print(f"Total Time Lapsed: {total_time_lapsed} seconds")
print(shortlisted_props.head())

980
1.5156791306187403
115C Yishun Ring Road
1000
1.5153659288907373
For Rent - 115C Yishun Ring Road
704 Yishun Avenue 5
1100
1.5139705688971938
For Rent - 704 Yishun Avenue 5
203 Yishun Street 21
900
1.5170709504615152
For Rent - 203 Yishun Street 21
217 Yishun Street 21
1200
1.5128075334611502
For Rent - 217 Yishun Street 21
149 Yishun Street 11
1000
1.5153659288907373
For Rent - 149 Yishun Street 11
733 Yishun Avenue 5
950
1.5161736280509812
For Rent - 733 Yishun Avenue 5

950
1.5161736280509812
641 Yishun Street 61
1000
1.5153659288907373
For Rent - 641 Yishun Street 61
296 Yishun Street 20
1200
1.5128075334611502
735 Yishun Street 72
1000
1.5153659288907373
For Rent - 735 Yishun Street 72
160 Yishun Street 11
1200
1.5128075334611502
712 Yishun Avenue 5
800
1.01920158044742
710 Yishun Avenue 5
900
1.5170709504615152
For Rent - 710 Yishun Avenue 5
Blk 435 Yishun Avenue 6
900
1.5170709504615152
For Rent - For Female Tenant @ Blk 435 Yishun Ave 6
721 Yishun Street 71
1100
1.5139705688971938
160 Yishun Street 11
1200
1.5128075334611502
288 Yishun Avenue 6
900
1.5170709504615152
For Rent - 288 Yishun Avenue 6
658 Yishun Avenue 4
550
0.027910315767007556
288 Yishun Avenue 6
900
1.5170709504615152
For Rent - 288 Yishun Avenue 6

1200
1.5128075334611502
205 Yishun Street 21
800
1.01920158044742

900
1.5170709504615152
750 Yishun Street 72
900
1.5170709504615152
For Rent - 750 Yishun Street 72
342C Yishun Ring Road
1200
1.5128075334611502
386 Yishun Ring Road
750
1.020479613523907
124 Yishun Street 11
600
0.025589160711112988
288 Yishun Avenue 6
900
1.5170709504615152
For Rent - 288 Yishun Avenue 6
735 Yishun Street 72
800
1.01920158044742
139 Yishun Ring Road
1000
1.5153659288907373
353 Yishun Ring Road
900
1.5170709504615152
For Rent - 353 Yishun Ring Road
142 Yishun Ring Road
900
1.5170709504615152
139 Yishun Ring Road
750
1.020479613523907
467A Yishun Avenue 6
900
1.5170709504615152
467A Yishun Avenue 6
900
1.5170709504615152
204 Yishun Street 21
800
1.01920158044742
21 Yishun Close
1000
1.5153659288907373
785 Yishun Avenue 2
850
1.5180736893945252
For Rent - 785 Yishun Avenue 2
840 Yishun Street 81
1200
1.5128075334611502
120 Yishun Ring Road
850
1.5180736893945252
For Rent - 120 Yishun Ring Road
Total Time Lapsed: 964.7538435459137 seconds
                          Property               Address  Price (S$/mo)  \
3   For Rent - 785 Yishun Avenue 2   785 Yishun Avenue 2            850
4  For Rent - 120 Yishun Ring Road  120 Yishun Ring Road            850
2  For Rent - 353 Yishun Ring Road  353 Yishun Ring Road            900
0  For Rent - 750 Yishun Street 72  750 Yishun Street 72            900
1   For Rent - 288 Yishun Avenue 6   288 Yishun Avenue 6            900

   Travel Time (mins)  Property Score  \
3                23.0        1.518074
4                26.5        1.518074
2                21.5        1.517071
0                22.0        1.517071
1                28.0        1.517071

                                               Links
3  https://www.propertyguru.com.sg/listing/hdb-fo...
4  https://www.propertyguru.com.sg/listing/hdb-fo...
2  https://www.propertyguru.com.sg/listing/hdb-fo...
0  https://www.propertyguru.com.sg/listing/hdb-fo...
1  https://www.propertyguru.com.sg/listing/hdb-fo...

In [28]:
# t.close()

In [29]:
shortlisted_props.head(20)

,Property,Address,Price (S$/mo),Travel Time (mins),Property Score,Links
3,For Rent - 785 Yishun Avenue 2,785 Yishun Avenue 2,850,23.0,1.518074,https://www.propertyguru.com.sg/listing/hdb-fo...
4,For Rent - 120 Yishun Ring Road,120 Yishun Ring Road,850,26.5,1.518074,https://www.propertyguru.com.sg/listing/hdb-fo...
2,For Rent - 353 Yishun Ring Road,353 Yishun Ring Road,900,21.5,1.517071,https://www.propertyguru.com.sg/listing/hdb-fo...
0,For Rent - 750 Yishun Street 72,750 Yishun Street 72,900,22.0,1.517071,https://www.propertyguru.com.sg/listing/hdb-fo...
1,For Rent - 288 Yishun Avenue 6,288 Yishun Avenue 6,900,28.0,1.517071,https://www.propertyguru.com.sg/listing/hdb-fo...